dependencies = {
	layers: [{
		name: "dojo.js",
		dependencies: [
			"dijit._base",
			"dijit._base.focus",
			"dijit._base.popup",
			"dijit._base.place",
			"dijit._base.scroll",
			"dijit._base.sniff",
			"dijit._base.typematic",
			"dijit._base.window",
			"dijit._base.wai",
			"dijit._Container",
			"dijit._HasDropDown",
			"dijit.Dialog",
			"dijit.DynamicTooltip",
			"dijit.form._FormValueMixin",
			"dijit.form._FormValueWidget",
			"dijit.form.ComboButton",
			"dijit.form.DropDownButton",
			"dijit.form.ToggleButton",
			"dijit.form._ToggleButtonMixin",
			"dijit.popup",
			"dijit.TooltipDialog",
			"dijit.typematic",
			"dijit.WidgetSet",
			"dojo._base.connect",
			"dojo.fx",
			"dojo.fx.Toggler",
			"dojo.io.iframe",
			"dojo.selector.acme",
			"dojox.charting.MouseInteractionSupport",
			"dojox.charting.widget.Chart2D",
			"dojox.charting.widget.Legend",
			"dojox.form.AppendUploader",
			"dojox.form.Uploader",
			"dojox.form.uploader.FileList",
			"dojox.form.uploader.InteractiveFileList",
			"dojox.form.uploader.plugins.HTML5",
			"dojox.form.uploader.plugins.IFrame",
			"dojox.gfx",
			"dojox.gfx.path",
			"dojox.gfx.shape",
			"dojox.gfx.svg",
			"dojox.html.ellipsis"
		]}
	],
	prefixes: [
		[ "dijit", "../dijit" ],
		[ "dojox", "../dojox" ]
	]
}
