#!/bin/sh

python <<%%%
from PepXML import *
#PepBinSearchAdvanced("/home/andrew/Desktop/g.pepBIN", {"NeutralMass": "2667.32495117188"})
PepBinSearchBasic("/home/andrew/Desktop/g.pepBIN", "SSPHNLDVLSKK")
%%%

#python <<%%%
#from PepXML import *
#PepXml2Bin("/home/andrew/Desktop/g.pepXML")
#print("Starting search")
##PepBinSearchBasic("/home/andrew/Desktop/g.pepBIN", "$search")
#PepBinSearchAdv("/home/andrew/Desktop/g.pepBIN", {"NeutralMass": 2667.32495117188})
#%%%



#python <<%%%
#from PepXML import *
#PepXml2Bin("/home/andrew/Desktop/g.pepXML")
#%%%
