#!/bin/sh

#python <<%%%
#from PepXML import *
##SearchAdvanced("/home/andrew/Desktop/g.pepBIN", {"NeutralMass": "2667.32495117188"})
#SearchBasic("/home/andrew/Desktop/g.pepBIN", "SSPHNLDVLSKK")
#%%%

python <<%%%
from PepXML import *
ToBinary("/home/andrew/Desktop/g.pepXML")
print("Starting search")
SearchBasic("/home/andrew/Desktop/g.pepBIN", "$search")
#SearchAdvanced("/home/andrew/Desktop/g.pepBIN", {"NeutralMass": 2667.32495117188})
%%%



#python <<%%%
#from PepXML import *
#ToBinary("/home/andrew/Desktop/g.pepXML")
#%%%
