#ifndef __REFERENCE_H__
	#define __REFERENCE_H__

	#define FILETYPE_MISSING 0x80 #any types with 0x80 set are missing
	#define FILETYPE_UNKNOWN 0
	#define FILETYPE_MZML 1
	#define FILETYPE_MGF 2
	#define FILETYPE_PEPXML 3
	#define FILETYPE_PEPXML_MASCOT 4
	#define FILETYPE_PEPXML_OMSSA 5
	#define FILETYPE_PEPXML_XTANDEM 6
	#define FILETYPE_PEPXML_COMPARE 7
	#define FILETYPE_PEPXML_PEPTIDEPROPHET 8
	#define FILETYPE_PEPXML_INTERPROPHET 9
	#define FILETYPE_PROTXML 10
	#define FILETYPE_PROTXML_PROTEINPROPHET 11

#endif
